 
"""Assignment-06

Automatically generated by Colaboratory.

 

Assignment-06 
Mahadi Hasan Mishuk
CE-D Roll:54
21SOECE11649

1- Demonstrate the use of the following functions of List Data Structure:

Operations on List: copy(), count(), extend(), index(), reverse(), sort()

Manipulating List: append(), insert(), pop(), remove(), clear()
"""

num=[1,2,3,4,5,6]
num2=num.copy()
print(num2)

num=[1,2,3,4,5,6,7]
cnt=num.count(4)
print(cnt)

name=["Mahadi","Hasan","Mishuk"]
salary=["12000","13000","13000"]
name.extend(salary)
print(name)

name=["Mahadi","Hasan","Mishuk"]
n=name.index("Hasan")
print(n)

num=[1,2,3,4,5,6]
num.reverse()
print(num)

num=[1,5,4,6,2]
num.sort()
print(num)

num=["Mahadi","Mishuk"]
num.insert(1,"Hasan")
print(num)

num=["Mahadi","Hasan","Mishuk","Mishuk"]
num.pop(2)
print(num)

num=["Mahadi","Hasan","Mishuk"]
num.remove("Hasan")
print(num)

num=["Mahadi","Hasan"]
num.clear()
print(num)




"""2- Write a Python program which matches the following output:

Input:

tuple1 = (10, 20, 30, 40, 50)

Output:

(50, 40, 30, 20, 10)
"""



tuple1=(10,20,30,40,50)
 
print(Reverse(tuple1))




"""3- What is the output of the following code? Explain your answer.

Code:

tuple1 = (0, 1, 2, 3)

tuple1[0] = 4

print(tuple1)
"""



Output of this code is erron because we know that in tuple the value of tuple is not changabele.

"""The list of items:  [6, 7, 8, 9, 10, 1, 2, 3, 4, 5]"""

num=[6,7,8,9,10,1,2,3,4,5]
sum=sum(num)
print("Sum of all item is="sum)

num=[6,7,8,9,10,1,2,3,4,5]
result=1
for i in num:
  result=result*i
print(result)

"""Largest item:  10"""

num=[6,7,8,9,10,1,2,3,4,5]
num.sort()
print(num)
print("Larhest number is=",num[-1])

num=[6,7,8,9,10,1,2,3,4,5]
num.sort()
print(num)
print("Smaler  number is=",num[0])




"""5- Write a Python program to convert a given tuple of positive integers into an integer.
Output:

Original tuple:
(1, 2, 3)
Convert the tuple into an integer:
123
Original tuple:
(10, 20, 40, 5, 70)
Convert the tuple into an integer:
102040570
"""

Num= (1, 4, 5)

 
print("The original tuple : " , num)

 
res = int(''.join(map(str, num)))

 
print("Tuple to integer conversion : " + str(res))




"""6- Write a Python program to convert a given string into a list of words."""

name = "Mahadi Hasan Mishuk"
print(name.split(' '))




"""7- What is the expected output of the following code?

mytuple = (1,4,5,6,3,4,4,5,6,63,2,1,3,45,5,5,5,5,5,5,6,8,9,0,2,1,3,524,56,5,7,8,8,9,6)

print(mytuple.count(5))

print(mytuple.index(9))
"""

mytuple = (1,4,5,6,3,4,4,5,6,63,2,1,3,45,5,5,5,5,5,5,6,8,9,0,2,1,3,524,56,5,7,8,8,9,6)

print(mytuple.count(5))

print(mytuple.index(9))